### PR TITLE
add missing vendored dependency

### PR DESCRIPTION
**Pull request by andir**
While trying to package this for [`nixpkgs`](https://github.com/nixos/nixpkgs) I ran into missing dependency issues. The `github.com/alecthomas/kingpin` module was being used but not properly vendored.

Since I haven't really done any Go development in a few years I tried my best to get that situation fixed. A combination of `govendor fetch` and `govendor update` did lead to the current state.

With my commit applied this project can be built with Nix so I expect it also to still work for other platforms.

---
This change is [Reviewable](https://reviewable.io/reviews/packethost/prometheus-packet-sd/1)

### CODE REVIEW

**Comment by jasmingacic** [comment]
Why not use Go modules instead of `govendor`?

**Comment by t0mk** [comment]
Hi @andir, thanks for the PR, I will take a look on this tomorrow. Yeah the deps should be solved somehow. Maybe go modules are way to go, as we use it in packngo. Thanks for the tip @jasmingacic

**Comment by t0mk** [comment]
hi @andir, I tried switch to Go Modules in the master branch, can you check if it works for you now?

I actually tried to use go modules from the beginning, but there was a problem with an ancient Prometheus depenency. So for my reference - it's necessary to explicitly put Prometheus version (or commig hash) in `go.mod`, otherwise it picks too old release. 
https://github.com/prometheus/prometheus/issues/5590

**Comment by t0mk** [comment]
This has hopefully been fixed (or made much worse) by using Go Modules. I'm closin this.

**Pull request closed without merging**
